name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        # type: (boolean/number/string/choice/environment)
        type: string
        default: Hello
        required: true
        description: A cheerful word
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"
